XKRT: xkrt Namespace Reference
xkrt Namespace Reference
Classes
struct distribution_t
struct driver_t
struct drivers_t
struct runtime_t
Main runtime system structure.
Typedefs
typedef xkrt_task_wait_counter_type_t task_wait_counter_type_t
typedef std::atomic< task_wait_counter_type_t > task_wait_counter_t
typedef xkrt_task_access_counter_t task_access_counter_t
typedef xkrt_task_flags_t task_flags_t
typedef xkrt_task_state_t task_state_t
typedef xkrt_task_flag_bitfield_t task_flag_bitfield_t
typedef xkrt_device_driver_id_t device_driver_id_t
typedef xkrt_device_unique_id_t device_unique_id_t
typedef xkrt_device_unique_id_bitfield_t device_unique_id_bitfield_t
typedef xkrt_driver_type_t driver_type_t
typedef xkrt_driver_type_bitfield_t driver_type_bitfield_t
typedef xkrt_access_concurrency_t access_concurrency_t
typedef xkrt_access_mode_t access_mode_t
typedef xkrt_access_scope_t access_scope_t
typedef xkrt_access_type_t access_type_t
typedef xkrt_matrix_storage_t matrix_storage_t
typedef xkrt_task_formats_t task_formats_t
typedef xkrt_task_format_t task_format_t
typedef xkrt_task_format_id_t task_format_id_t
typedef xkrt_task_format_func_t task_format_func_t
typedef xkrt_task_format_target_t task_format_target_t
typedef xkrt_command_callback_index_t command_callback_index_t
typedef xkrt_command_queue_type_t command_queue_type_t
typedef xkrt_command_queue_list_counter_t command_queue_list_counter_t
typedef xkrt_driver_module_fn_t driver_module_fn_t
typedef xkrt_driver_module_format_t driver_module_format_t
typedef xkrt_driver_module_t driver_module_t
typedef xkrt_power_counter_t power_counter_t
typedef xkrt_power_t power_t
typedef xkrt_prog_launcher_t prog_launcher_t
typedef struct xkrt::driver_t driver_t
typedef struct xkrt::drivers_t drivers_t
typedef enum xkrt::distribution_type_t distribution_type_t
typedef struct xkrt::distribution_t distribution_t
Enumerations
enum distribution_type_t { XKRT_DISTRIBUTION_TYPE_CYCLIC1D , XKRT_DISTRIBUTION_TYPE_CYCLIC2D , XKRT_DISTRIBUTION_TYPE_CYCLIC2DBLOCK }
Functions
void * team_parallel_for_main (runtime_t *runtime, team_t *team, thread_t *thread)
Main routine for parallel for execution.
device_t * driver_device_get (driver_t *driver, device_unique_id_t driver_device_id)
device_unique_id_t distribution1D_get (distribution_t *d, size_t t)
device_unique_id_t distribution2D_get (distribution_t *d, size_t tm, size_t tn)
void distribution1D_init (distribution_t *d, distribution_type_t type, size_t count, size_t size, size_t bs)
void distribution2D_init (distribution_t *d, distribution_type_t type, size_t count, size_t m, size_t n, size_t mb, size_t nb)
Typedef Documentation
access_concurrency_t
typedef xkrt_access_concurrency_t xkrt::access_concurrency_t
Definition at line 77 of file types.h.
access_mode_t
typedef xkrt_access_mode_t xkrt::access_mode_t
Definition at line 78 of file types.h.
access_scope_t
typedef xkrt_access_scope_t xkrt::access_scope_t
Definition at line 79 of file types.h.
access_type_t
typedef xkrt_access_type_t xkrt::access_type_t
Definition at line 80 of file types.h.
command_callback_index_t
typedef xkrt_command_callback_index_t xkrt::command_callback_index_t
Definition at line 89 of file types.h.
command_queue_list_counter_t
typedef xkrt_command_queue_list_counter_t xkrt::command_queue_list_counter_t
Definition at line 91 of file types.h.
command_queue_type_t
typedef xkrt_command_queue_type_t xkrt::command_queue_type_t
Definition at line 90 of file types.h.
device_driver_id_t
typedef xkrt_device_driver_id_t xkrt::device_driver_id_t
Definition at line 70 of file types.h.
device_unique_id_bitfield_t
typedef xkrt_device_unique_id_bitfield_t xkrt::device_unique_id_bitfield_t
Definition at line 72 of file types.h.
device_unique_id_t
typedef xkrt_device_unique_id_t xkrt::device_unique_id_t
Definition at line 71 of file types.h.
distribution_t
typedef struct xkrt::distribution_t xkrt::distribution_t
distribution_type_t
typedef enum xkrt::distribution_type_t xkrt::distribution_type_t
driver_module_fn_t
typedef xkrt_driver_module_fn_t xkrt::driver_module_fn_t
Definition at line 93 of file types.h.
driver_module_format_t
typedef xkrt_driver_module_format_t xkrt::driver_module_format_t
Definition at line 94 of file types.h.
driver_module_t
typedef xkrt_driver_module_t xkrt::driver_module_t
Definition at line 95 of file types.h.
driver_t
typedef struct xkrt::driver_t xkrt::driver_t
driver_type_bitfield_t
typedef xkrt_driver_type_bitfield_t xkrt::driver_type_bitfield_t
Definition at line 75 of file types.h.
driver_type_t
typedef xkrt_driver_type_t xkrt::driver_type_t
Definition at line 74 of file types.h.
drivers_t
typedef struct xkrt::drivers_t xkrt::drivers_t
matrix_storage_t
typedef xkrt_matrix_storage_t xkrt::matrix_storage_t
Definition at line 81 of file types.h.
power_counter_t
typedef xkrt_power_counter_t xkrt::power_counter_t
Definition at line 97 of file types.h.
power_t
typedef xkrt_power_t xkrt::power_t
Definition at line 98 of file types.h.
prog_launcher_t
typedef xkrt_prog_launcher_t xkrt::prog_launcher_t
Definition at line 100 of file types.h.
task_access_counter_t
typedef xkrt_task_access_counter_t xkrt::task_access_counter_t
Definition at line 65 of file types.h.
task_flag_bitfield_t
typedef xkrt_task_flag_bitfield_t xkrt::task_flag_bitfield_t
Definition at line 68 of file types.h.
task_flags_t
typedef xkrt_task_flags_t xkrt::task_flags_t
Definition at line 66 of file types.h.
task_format_func_t
typedef xkrt_task_format_func_t xkrt::task_format_func_t
Definition at line 86 of file types.h.
task_format_id_t
typedef xkrt_task_format_id_t xkrt::task_format_id_t
Definition at line 85 of file types.h.
task_format_t
typedef xkrt_task_format_t xkrt::task_format_t
Definition at line 84 of file types.h.
task_format_target_t
typedef xkrt_task_format_target_t xkrt::task_format_target_t
Definition at line 87 of file types.h.
task_formats_t
typedef xkrt_task_formats_t xkrt::task_formats_t
Definition at line 83 of file types.h.
task_state_t
typedef xkrt_task_state_t xkrt::task_state_t
Definition at line 67 of file types.h.
task_wait_counter_t
typedef std::atomic<task_wait_counter_type_t> xkrt::task_wait_counter_t
Definition at line 64 of file types.h.
task_wait_counter_type_t
typedef xkrt_task_wait_counter_type_t xkrt::task_wait_counter_type_t
Definition at line 63 of file types.h.
Enumeration Type Documentation
distribution_type_t
enum xkrt::distribution_type_t
Enumerator
XKRT_DISTRIBUTION_TYPE_CYCLIC1D
XKRT_DISTRIBUTION_TYPE_CYCLIC2D
XKRT_DISTRIBUTION_TYPE_CYCLIC2DBLOCK
Definition at line 47 of file distribution.h.
Function Documentation
distribution1D_get()
device_unique_id_t xkrt::distribution1D_get (distribution_t * d, size_t t)
References distribution1D_get().
Referenced by distribution1D_get().
distribution1D_init()
void xkrt::distribution1D_init (distribution_t * d, distribution_type_t type, size_t count, size_t size, size_t bs)
References distribution1D_init().
Referenced by distribution1D_init().
distribution2D_get()
device_unique_id_t xkrt::distribution2D_get (distribution_t * d, size_t tm, size_t tn)
References distribution2D_get().
Referenced by distribution2D_get().
distribution2D_init()
void xkrt::distribution2D_init (distribution_t * d, distribution_type_t type, size_t count, size_t m, size_t n, size_t mb, size_t nb)
References distribution2D_init().
Referenced by distribution2D_init().
driver_device_get()
device_t * xkrt::driver_device_get (driver_t * driver, device_unique_id_t driver_device_id)
References driver_device_get().
Referenced by driver_device_get().
team_parallel_for_main()
void * xkrt::team_parallel_for_main (runtime_t * runtime, team_t * team, thread_t * thread)
Main routine for parallel for execution.
Parameters
runtime Pointer to the runtime system
team Pointer to the team
thread Pointer to the thread
Returns
Thread return value
References team_parallel_for_main().
Referenced by team_parallel_for_main().