XKRT: xkrt::runtime_t Struct Reference
xkrt::runtime_t Struct Reference
Main runtime system structure.
#include <runtime.h>
Public Types
enum state_t : uint8_t { DEINITIALIZED = 0 , INITIALIZED = 1 }
Runtime system state enumeration.
typedef std::function< void(runtime_t *, device_t *, task_t *)> task_routine_t
typedef std::function< void(task_t *, access_t *)> task_accesses_setter_t
typedef std::function< bool(task_t *, access_t *)> task_split_condition_t
typedef std::function< void(thread_t *thread)> team_parallel_for_func_t
typedef std::function< void(thread_t *thread, const int i)> team_parallel_for_i_func_t
Public Member Functions
int init (void)
Initialize the runtime system.
int deinit (void)
Deinitialize the runtime system.
void reset (void)
Reset the runtime.
void reset_coherence_controllers (void)
void reset_dependence_controllers (void)
int command_submit (const device_unique_id_t device_unique_id, command_t *command)
int task_emit_command (const device_unique_id_t device_unique_id, const command_queue_type_t qtype, const ocg::command_type_t ctype, const command_flag_t flags, const std::function< void(command_t *)> builder)
void copy (const device_unique_id_t device_unique_id, const size_t size, const device_unique_id_t dst_device_unique_id, const uintptr_t dst_device_addr, const device_unique_id_t src_device_unique_id, const uintptr_t src_device_addr, const callback_t &callback)
Submit a 1D copy command to a device queue.
void copy (const device_unique_id_t device_unique_id, const memory_view_t &host_view, const device_unique_id_t dst_device_unique_id, const memory_replica_view_t &dst_device_view, const device_unique_id_t src_device_unique_id, const memory_replica_view_t &src_device_view, const callback_t &callback)
Submit a 2D copy command to a device queue.
void memory_copy_async (const device_unique_id_t device_unique_id, const size_t size, const device_unique_id_t dst_device_unique_id, const uintptr_t dst_device_addr, const device_unique_id_t src_device_unique_id, const uintptr_t src_device_addr, int n)
Asynchronously copy memory by spawning n parallel tasks.
void distribute_async (distribution_type_t type, void *ptr, size_t size, size_t nb, size_t h)
Asynchronously distribute memory uniformly across all devices, by spawning empty tasks that reads a sub segment.
void distribute_async (distribution_type_t type, void **ptr, size_t chunk_size, unsigned int n)
Asynchronously distribute array of segments across all devices, by spawning 'n' empty tasks that read each segment.
void distribute_async (distribution_type_t type, matrix_storage_t storage, void *ptr, size_t ld, size_t m, size_t n, size_t mb, size_t nb, size_t sizeof_type, size_t hx, size_t hy)
Asynchronously distribute a matrix across all devices.
int file_read_async (int fd, void *buffer, const size_t size, int n)
Asynchronously read from file using parallel tasks.
int file_write_async (int fd, void *buffer, const size_t size, int n)
Asynchronously write to file using parallel tasks.
void foreach (const uintptr_t p, const size_t size, int n, const std::function< void(const int, const uintptr_t, const uintptr_t)> &func)
Iterate over memory segment chunks and apply a function.
void memory_device_preallocate_ensure (const device_unique_id_t device_unique_id, const int memory_id)
Ensure chunk0 is preallocated on the device.
area_chunk_t * memory_device_allocate_on (const device_unique_id_t device_unique_id, const size_t size, const int memory_id)
Allocate memory on a specific device memory bank.
area_chunk_t * memory_device_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate memory on device's default memory bank.
void memory_device_deallocate (const device_unique_id_t device_unique_id, area_chunk_t *chunk)
Deallocate a device memory chunk.
void memory_device_deallocate_all (const device_unique_id_t device_unique_id)
Deallocate all memory previously allocated on the device.
void * memory_host_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate host memory using a device driver.
void memory_host_deallocate (const device_unique_id_t device_unique_id, void *mem, const size_t size)
Deallocate host memory using a device driver.
void * memory_unified_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate unified memory accessible by both host and device.
void memory_unified_deallocate (const device_unique_id_t device_unique_id, void *mem, const size_t size)
Deallocate unified memory.
void memory_noncoherent_alloc (device_unique_id_t device_unique_id, void *ptr, size_t size)
Synchronously allocate a non-coherent device replica.
void memory_noncoherent_alloc (device_unique_id_t device_unique_id, matrix_storage_t storage, void *ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Synchronously allocate a non-coherent device replica for a matrix.
void memory_coherent_async (device_unique_id_t device_unique_id, void *ptr, size_t size)
Spawn an empty task with a read access on the passed segment.
void memory_coherent_async (device_unique_id_t device_unique_id, void *ptr, size_t size, int n)
void memory_coherent_async (device_unique_id_t device_unique_id, matrix_storage_t storage, void *ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Spawn an empty task with a read access on the passed matrix.
void memory_coherent_sync (device_unique_id_t device_unique_id, void *ptr, size_t size)
Spawn an empty undeferred task with a read access on the passed segment.
void memory_coherent_sync (device_unique_id_t device_unique_id, matrix_storage_t storage, void *ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Spawn an empty undeferred task with a read access on the passed matrix.
int memory_unified_advise (const device_unique_id_t device_unique_id, const void *addr, const size_t size)
Hint to unified memory system about future device access.
int memory_unified_prefetch (const device_unique_id_t device_unique_id, const void *addr, const size_t size)
Prefetch unified memory to make it coherent on device.
int memory_register (void *ptr, size_t size)
Synchronously register memory for device access (pinning)
int memory_unregister (void *ptr, size_t size)
Synchronously unregister memory.
int memory_register_async (void *ptr, size_t size)
Asynchronously register memory using a single task.
int memory_unregister_async (void *ptr, size_t size)
Asynchronously unregister memory using a single task.
int memory_register_async (team_t *team, void *ptr, const size_t size, int n)
Asynchronously register memory using parallel tasks.
int memory_unregister_async (team_t *team, void *ptr, const size_t size, int n)
Asynchronously unregister memory using parallel tasks.
int memory_touch_async (team_t *team, void *ptr, const size_t size, int n)
Asynchronously touch memory pages to ensure they're resident.
int memory_register_async (void *ptr, const size_t size, int n)
Asynchronously register memory using default host team.
int memory_unregister_async (void *ptr, const size_t size, int n)
Asynchronously unregister memory using default host team.
int memory_touch_async (void *ptr, const size_t size, int n)
Asynchronously touch memory pages to ensure they're resident.
void task_accesses_link (task_t *task, access_t *accesses, task_access_counter_t n)
void task_accesses_put (task_t *task, access_t *accesses, task_access_counter_t n)
void task_accesses_resolve (task_t *task, access_t *accesses, task_access_counter_t n)
void task_accesses_resolve (access_t *accesses, task_access_counter_t n)
template<typename... Args>
void task_commit (task_t *task, void(*F)(Args..., task_t *), Args... args)
void task_commit (task_t *task)
void task_detachable_decr (task_t *task)
void task_detachable_incr (task_t *task)
void task_complete (task_t *task)
void task_wait (void)
void task_enqueue (task_t *task)
void task_thread_enqueue (thread_t *thread, task_t *task)
void task_team_enqueue (team_t *team, task_t *task)
task_t * task_dup (const task_t *task)
template<bool use_thread_stack = true>
task_t * task_new (const task_format_id_t fmtid, task_flag_bitfield_t flags, const void *args, const size_t args_size, const task_access_counter_t n_accesses)
void task_deallocate_all (void)
template<task_flag_bitfield_t flags>
task_t * task_instanciate (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t &set_accesses, const task_split_condition_t &split_condition, const void *args, const size_t args_size, const task_format_id_t fmtid)
template<task_flag_bitfield_t flags>
task_t * task_instanciate (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t &set_accesses, const task_split_condition_t &split_condition, const task_routine_t &f)
template<task_flag_bitfield_t flags>
void task_spawn (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t &set_accesses, const task_split_condition_t &split_condition, const task_routine_t &f)
Spawn a task in the currently executing thread team.
void task_spawn (const task_routine_t &f)
template<task_access_counter_t ac>
void task_spawn (const task_accesses_setter_t &set_accesses, const task_split_condition_t &split_condition, const task_routine_t &f)
template<task_access_counter_t ac>
void task_spawn (const task_accesses_setter_t &set_accesses, const task_routine_t &f)
void team_create (team_t *team)
Create a new thread team.
template<bool worksteal = false>
void team_barrier (team_t *team, thread_t *thread=NULL)
Synchronization barrier - wait until all threads reach this point.
void team_join (team_t *team)
Wait until all threads have finished and destroy the team.
void team_critical_begin (team_t *team)
Enter a critical section (mutual exclusion)
void team_critical_end (team_t *team)
Exit a critical section.
void team_parallel_for (team_t *team, team_parallel_for_func_t func)
Execute a parallel for loop across team threads (blocking)
void team_parallel_for (team_t *team, team_parallel_for_i_func_t func, const int up, const int low=0, const int incr=1)
template<int UP, int LOW = 0, int INCR = 1>
void team_parallel_for (team_t *team, team_parallel_for_i_func_t func)
void team_task_commit (team_t *team, task_t *task)
template<task_flag_bitfield_t flags>
void team_task_spawn (team_t *team, const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t &set_accesses, const std::function< bool(task_t *, access_t *)> &split_condition, const std::function< void(runtime_t *, device_t *, task_t *)> &f)
Spawn a task within a specific team.
team_t * team_get (const driver_type_t type, const device_driver_id_t device_driver_id)
Retrieve the thread team for a specific device.
team_t * team_get (const driver_type_t type)
Retrieve the thread team for a specific driver type.
team_t * team_get_any (const driver_type_bitfield_t types)
Retrieve the first available team from multiple driver types.
void power_start (const device_unique_id_t device_unique_id, power_t *pwr)
Start recording energy consumption for a device.
void power_stop (const device_unique_id_t device_unique_id, power_t *pwr)
Stop recording and retrieve energy consumption.
driver_t * driver_get (const driver_type_t type)
Get a driver by type.
device_t * device_get (const device_unique_id_t device_unique_id)
Get a device by its global identifier.
device_unique_id_bitfield_t devices_get (const driver_type_t type)
Get bitfield of all devices for a given driver type.
unsigned int get_ndevices (void)
Get the number of committed (active) devices.
unsigned int get_ndevices_max (void)
Get the maximum number of devices available.
void task_formats_init (void)
Initializes the task formats repository.
task_format_id_t task_format_create (const task_format_t *format)
Creates and registers a new task format.
task_format_id_t task_format_put (const char *label)
Allocates a new task format ID without setting its data.
int task_format_set (task_format_id_t fmtid, task_format_target_t target, task_format_func_t func)
Sets the function for a specific target on the passed task format.
task_format_t * task_format_get (task_format_id_t fmtid)
Retrieves a task format by its ID.
template<bool synchronous>
void task_prog_launch (device_t *device, task_t *task, prog_launcher_t launcher)
void task_dependency_graph_record_start (task_dependency_graph_t *tdg, bool execute_commands)
void task_dependency_graph_replay (task_dependency_graph_t *tdg)
void task_dependency_graph_record_stop (void)
void task_dependency_graph_destroy (task_dependency_graph_t *tdg)
void command_graph_from_task_dependency_graph (task_dependency_graph_t *tdg, command_graph_t *cg)
void command_graph_replay (command_graph_t *cg)
void command_graph_destroy (command_graph_t *cg)
void stats_report (void)
Report collected runtime statistics.
Static Public Member Functions
static void task_enqueue (runtime_t *runtime, task_t *task)
static void task_thread_enqueue (runtime_t *runtime, thread_t *thread, task_t *task)
static void task_team_enqueue (runtime_t *runtime, team_t *team, task_t *task)
static void thread_getaffinity (cpu_set_t &cpuset)
Retrieve the CPU affinity mask of the calling thread.
static void thread_setaffinity (cpu_set_t &cpuset)
Bind the calling thread to the specified CPU set.
Public Attributes
std::atomic< state_t > state
Current runtime state (atomic)
drivers_t drivers
List of registered device drivers.
struct {
task_formats_t list
Complete list of task formats.
task_format_id_t host_capture
Host capture task format ID.
task_format_id_t memory_copy_async
Async memory copy task format ID.
task_format_id_t memory_touch_async
Async memory touch task format ID.
task_format_id_t memory_register_async
Async memory registration format ID.
task_format_id_t memory_unregister_async
Async memory unregistration format ID.
task_format_id_t file_read_async
Async file read task format ID.
task_format_id_t file_write_async
Async file write task format ID.
} formats
Task format registry.
conf_t conf
User configuration.
RouterAffinity router
Memory router used by the MCC.
std::map< uintptr_t, size_t > registered_memory
Map of registered memory segments (addr -> size)
IntervalSet< uintptr_t > registered_pages
Set of registered memory page intervals.
hwloc_topology_t topology
Hardware locality topology (read-only, initialized at startup)
struct {
struct {
stats_int_t submitted
Number of tasks submitted.
stats_int_t commited
Number of tasks committed.
stats_int_t completed
Number of tasks completed.
} tasks [XKRT_TASK_FORMAT_MAX]
struct {
stats_int_t registered
Memory regions registered.
stats_int_t unregistered
Memory regions unregistered.
struct {
struct {
stats_int_t device
Device-side advised allocations.
stats_int_t host
Host-side advised allocations.
} advised
struct {
stats_int_t device
Device-side prefetched data.
stats_int_t host
Host-side prefetched data.
} prefetched
} unified
} memory
} stats
Runtime statistics collection.
Detailed Description
Main runtime system structure.
This structure contains all the state and configuration for the XKRT runtime system, including device drivers, task formats, memory management, and threading.
Definition at line 69 of file runtime.h.
Member Typedef Documentation
task_accesses_setter_t
typedef std::function<void(task_t *, access_t *)> xkrt::runtime_t::task_accesses_setter_t
Definition at line 807 of file runtime.h.
task_routine_t
typedef std::function<void(runtime_t *, device_t *, task_t *)> xkrt::runtime_t::task_routine_t
Definition at line 806 of file runtime.h.
task_split_condition_t
typedef std::function<bool(task_t *, access_t *)> xkrt::runtime_t::task_split_condition_t
Definition at line 808 of file runtime.h.
team_parallel_for_func_t
typedef std::function<void(thread_t * thread)> xkrt::runtime_t::team_parallel_for_func_t
Definition at line 1064 of file runtime.h.
team_parallel_for_i_func_t
typedef std::function<void(thread_t * thread, const int i)> xkrt::runtime_t::team_parallel_for_i_func_t
Definition at line 1065 of file runtime.h.
Member Enumeration Documentation
state_t
enum xkrt::runtime_t::state_t : uint8_t
Runtime system state enumeration.
Enumerator
DEINITIALIZED
Runtime is not initialized.
INITIALIZED
Runtime is initialized and ready.
Definition at line 74 of file runtime.h.
Member Function Documentation
command_graph_destroy()
void xkrt::runtime_t::command_graph_destroy (command_graph_t * cg)
Destroy a command graph
command_graph_from_task_dependency_graph()
void xkrt::runtime_t::command_graph_from_task_dependency_graph (task_dependency_graph_t * tdg, command_graph_t * cg)
Construct a command graph from a task dependency graph Dependencies are set between commands to ensure the same order of execution as per the task scheduling enforced.
command_graph_replay()
void xkrt::runtime_t::command_graph_replay (command_graph_t * cg)
Launch and wait for completion of every commands of the graph
command_submit()
int xkrt::runtime_t::command_submit (const device_unique_id_t device_unique_id, command_t * command)
Submit a command to the passed device
copy() [1/2]
void xkrt::runtime_t::copy (const device_unique_id_t device_unique_id, const memory_view_t & host_view, const device_unique_id_t dst_device_unique_id, const memory_replica_view_t & dst_device_view, const device_unique_id_t src_device_unique_id, const memory_replica_view_t & src_device_view, const callback_t & callback)
Submit a 2D copy command to a device queue.
Parameters
device_unique_id Global ID of the device executing the copy
host_view Host memory view
dst_device_unique_id Destination device global ID
dst_device_view Destination device memory replica view
src_device_unique_id Source device global ID
src_device_view Source device memory replica view
callback Callback function to invoke upon completion
copy() [2/2]
void xkrt::runtime_t::copy (const device_unique_id_t device_unique_id, const size_t size, const device_unique_id_t dst_device_unique_id, const uintptr_t dst_device_addr, const device_unique_id_t src_device_unique_id, const uintptr_t src_device_addr, const callback_t & callback)
Submit a 1D copy command to a device queue.
Parameters
device_unique_id Global ID of the device executing the copy
size Number of bytes to copy
dst_device_unique_id Destination device global ID
dst_device_addr Destination device address
src_device_unique_id Source device global ID
src_device_addr Source device address
callback Callback function to invoke upon command completion
deinit()
int xkrt::runtime_t::deinit (void)
Deinitialize the runtime system.
Cleans up all resources, destroys drivers and task formats
Returns
0 on success, non-zero on error
device_get()
device_t * xkrt::runtime_t::device_get (const device_unique_id_t device_unique_id)
Get a device by its global identifier.
Parameters
device_unique_id Global device identifier
Returns
Pointer to the device, or nullptr if not found
devices_get()
device_unique_id_bitfield_t xkrt::runtime_t::devices_get (const driver_type_t type)
Get bitfield of all devices for a given driver type.
Parameters
type Driver type
Returns
Bitfield with bits set for each available device
distribute_async() [1/3]
void xkrt::runtime_t::distribute_async (distribution_type_t type, matrix_storage_t storage, void * ptr, size_t ld, size_t m, size_t n, size_t mb, size_t nb, size_t sizeof_type, size_t hx, size_t hy)
Asynchronously distribute a matrix across all devices.
Parameters
type Distribution type (e.g., 2D block-cyclic)
storage Matrix storage layout (row-major, column-major)
ptr Pointer to matrix data
ld Leading dimension of the matrix
m Number of rows
n Number of columns
mb Row block size
nb Column block size
sizeof_type Size of each matrix element in bytes
hx Horizontal halo/overlap size
hy Vertical halo/overlap size
distribute_async() [2/3]
void xkrt::runtime_t::distribute_async (distribution_type_t type, void ** ptr, size_t chunk_size, unsigned int n)
Asynchronously distribute array of segments across all devices, by spawning 'n' empty tasks that read each segment.
Parameters
type Distribution type
ptr Array of pointers to memory segments
chunk_size Size of each chunk
n Number of chunks
distribute_async() [3/3]
void xkrt::runtime_t::distribute_async (distribution_type_t type, void * ptr, size_t size, size_t nb, size_t h)
Asynchronously distribute memory uniformly across all devices, by spawning empty tasks that reads a sub segment.
Parameters
type Distribution type (e.g., block, cyclic)
ptr Pointer to the memory segment
size Size of the memory segment
nb Block size for distribution
h Halo/overlap size
driver_get()
driver_t * xkrt::runtime_t::driver_get (const driver_type_t type)
Get a driver by type.
Parameters
type Driver type to retrieve
Returns
Pointer to the driver, or nullptr if not found
file_read_async()
int xkrt::runtime_t::file_read_async (int fd, void * buffer, const size_t size, int n)
Asynchronously read from file using parallel tasks.
Spawns 'n' tasks where each task i in [0..n-1]:
oi = i*size/n (file offset)
ai = ptr + oi (buffer address)
bi = MIN(ai+size/n, size)
si = bi - ai (bytes to read)
Access: write on Interval(ai, bi)
Routine: fseek to 'oi' and read 'si' bytes to [ai..bi]
Parameters
fd File descriptor
buffer Destination buffer
size Total bytes to read
n Number of parallel read tasks
Returns
0 on success, non-zero on error
file_write_async()
int xkrt::runtime_t::file_write_async (int fd, void * buffer, const size_t size, int n)
Asynchronously write to file using parallel tasks.
Spawns 'n' tasks where each task i in [0..n-1]:
oi = i*size/n (file offset)
ai = ptr + oi (buffer address)
bi = MIN(ai+size/n, size)
si = bi - ai (bytes to write)
Access: read on Interval(ai, bi)
Routine: fseek to 'oi' and write 'si' bytes from [ai..bi]
Parameters
fd File descriptor
buffer Source buffer
size Total bytes to write
n Number of parallel write tasks
Returns
0 on success, non-zero on error
foreach()
void xkrt::runtime_t::foreach (const uintptr_t p, const size_t size, int n, const std::function< void(const int, const uintptr_t, const uintptr_t)> & func) inline
Iterate over memory segment chunks and apply a function.
Divides the memory segment [p, p+size) into n chunks and calls func(i, a, b) for each chunk where i is the chunk index and [a, b) is the address range.
Parameters
p Base address of memory segment
size Total size in bytes
n Number of chunks
func Function to call for each chunk: func(index, start_addr, end_addr)
Definition at line 361 of file runtime.h.
get_ndevices()
unsigned int xkrt::runtime_t::get_ndevices (void)
Get the number of committed (active) devices.
Returns
Number of devices currently in use
get_ndevices_max()
unsigned int xkrt::runtime_t::get_ndevices_max (void)
Get the maximum number of devices available.
Returns
Maximum device count
init()
int xkrt::runtime_t::init (void)
Initialize the runtime system.
Loads devices, drivers and creates task formats
Returns
0 on success, non-zero on error
memory_coherent_async() [1/3]
void xkrt::runtime_t::memory_coherent_async (device_unique_id_t device_unique_id, matrix_storage_t storage, void * ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Spawn an empty task with a read access on the passed matrix.
Parameters
device_unique_id Global device identifier
storage Matrix storage layout
ptr Host matrix pointer
ld Leading dimension
m Number of rows
n Number of columns
sizeof_type Size of each element in bytes
memory_coherent_async() [2/3]
void xkrt::runtime_t::memory_coherent_async (device_unique_id_t device_unique_id, void * ptr, size_t size)
Spawn an empty task with a read access on the passed segment.
Parameters
device_unique_id Global device identifier
ptr Host memory pointer
size Size in bytes
memory_coherent_async() [3/3]
void xkrt::runtime_t::memory_coherent_async (device_unique_id_t device_unique_id, void * ptr, size_t size, int n)
memory_coherent_sync() [1/2]
void xkrt::runtime_t::memory_coherent_sync (device_unique_id_t device_unique_id, matrix_storage_t storage, void * ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Spawn an empty undeferred task with a read access on the passed matrix.
Parameters
device_unique_id Global device identifier
storage Matrix storage layout
ptr Host matrix pointer
ld Leading dimension
m Number of rows
n Number of columns
sizeof_type Size of each element in bytes
memory_coherent_sync() [2/2]
void xkrt::runtime_t::memory_coherent_sync (device_unique_id_t device_unique_id, void * ptr, size_t size)
Spawn an empty undeferred task with a read access on the passed segment.
Parameters
device_unique_id Global device identifier
ptr Host memory pointer
size Size in bytes
memory_copy_async()
void xkrt::runtime_t::memory_copy_async (const device_unique_id_t device_unique_id, const size_t size, const device_unique_id_t dst_device_unique_id, const uintptr_t dst_device_addr, const device_unique_id_t src_device_unique_id, const uintptr_t src_device_addr, int n)
Asynchronously copy memory by spawning n parallel tasks.
Spawns 'n' tasks where each task i in [0..n-1]:
oi = i*size/n (offset)
ai = ptr + oi (start address)
bi = MIN(ai+size/n, size) (end address)
si = bi - ai (chunk size)
Accesses: virtual read on Interval(src.ai, src.bi)
Routine: submit a copy command for this chunk
Parameters
device_unique_id Global ID of the device executing the copy
size Total number of bytes to copy
dst_device_unique_id Destination device global ID
dst_device_addr Destination device base address
src_device_unique_id Source device global ID
src_device_addr Source device base address
n Number of parallel tasks to spawn
memory_device_allocate()
area_chunk_t * xkrt::runtime_t::memory_device_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate memory on device's default memory bank.
Parameters
device_unique_id Global device identifier
size Size in bytes to allocate
Returns
Pointer to allocated chunk, or nullptr on failure
memory_device_allocate_on()
area_chunk_t * xkrt::runtime_t::memory_device_allocate_on (const device_unique_id_t device_unique_id, const size_t size, const int memory_id)
Allocate memory on a specific device memory bank.
Parameters
device_unique_id Global device identifier
size Size in bytes to allocate
memory_id Device memory index (bank)
Returns
Pointer to allocated chunk, or nullptr on failure
memory_device_deallocate()
void xkrt::runtime_t::memory_device_deallocate (const device_unique_id_t device_unique_id, area_chunk_t * chunk)
Deallocate a device memory chunk.
Parameters
device_unique_id Global device identifier
chunk Pointer to chunk to deallocate
memory_device_deallocate_all()
void xkrt::runtime_t::memory_device_deallocate_all (const device_unique_id_t device_unique_id)
Deallocate all memory previously allocated on the device.
Parameters
device_unique_id Global device identifier
memory_device_preallocate_ensure()
void xkrt::runtime_t::memory_device_preallocate_ensure (const device_unique_id_t device_unique_id, const int memory_id)
Ensure chunk0 is preallocated on the device.
Parameters
device_unique_id Global device identifier
memory_id Device memory index
memory_host_allocate()
void * xkrt::runtime_t::memory_host_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate host memory using a device driver.
Parameters
device_unique_id Global device identifier (determines which driver to use)
size Size in bytes to allocate
Returns
Pointer to allocated memory, or nullptr on failure
memory_host_deallocate()
void xkrt::runtime_t::memory_host_deallocate (const device_unique_id_t device_unique_id, void * mem, const size_t size)
Deallocate host memory using a device driver.
Parameters
device_unique_id Global device identifier (determines which driver to use)
mem Pointer to memory to deallocate
size Size in bytes
memory_noncoherent_alloc() [1/2]
void xkrt::runtime_t::memory_noncoherent_alloc (device_unique_id_t device_unique_id, matrix_storage_t storage, void * ptr, size_t ld, size_t m, size_t n, size_t sizeof_type)
Synchronously allocate a non-coherent device replica for a matrix.
Parameters
device_unique_id Global device identifier
storage Matrix storage layout
ptr Host matrix pointer
ld Leading dimension
m Number of rows
n Number of columns
sizeof_type Size of each element in bytes
memory_noncoherent_alloc() [2/2]
void xkrt::runtime_t::memory_noncoherent_alloc (device_unique_id_t device_unique_id, void * ptr, size_t size)
Synchronously allocate a non-coherent device replica.
Parameters
device_unique_id Global device identifier
ptr Host memory pointer
size Size in bytes
memory_register()
int xkrt::runtime_t::memory_register (void * ptr, size_t size)
Synchronously register memory for device access (pinning)
TODO: is it 'legal' to have concurrently
host thread A writing to memory [a..b]
host thread B pinning memory [a..b] ? Can't find any doc on it, so for now, assuming it is not
Spawn 'n' tasks so that each task i in [0..n-1] ai = ptr + i*size/n bi = MIN(ai+size/n, size)
access - write on Interval(ai, bi)
virtual commutative write on NULL
routine - register/unregister/touch [ai..bi]
Parameters
ptr Memory pointer
size Size in bytes
Returns
0 on success, non-zero on error
memory_register_async() [1/3]
int xkrt::runtime_t::memory_register_async (team_t * team, void * ptr, const size_t size, int n)
Asynchronously register memory using parallel tasks.
Spawns 'n' tasks where each task i in [0..n-1]:
ai = ptr + i*size/n
bi = MIN(ai+size/n, size)
Access: write on Interval(ai, bi), virtual commutative write on NULL
Routine: register [ai..bi]
Note
Assumes it is NOT safe to have concurrent host writes during registration
Parameters
team Thread team to use for task execution
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
memory_register_async() [2/3]
int xkrt::runtime_t::memory_register_async (void * ptr, const size_t size, int n) inline
Asynchronously register memory using default host team.
Convenience wrapper that uses the host driver's team
Parameters
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
Definition at line 664 of file runtime.h.
References XKRT_DRIVER_TYPE_HOST.
memory_register_async() [3/3]
int xkrt::runtime_t::memory_register_async (void * ptr, size_t size)
Asynchronously register memory using a single task.
Parameters
ptr Memory pointer
size Size in bytes
Returns
0 on success, non-zero on error
memory_touch_async() [1/2]
int xkrt::runtime_t::memory_touch_async (team_t * team, void * ptr, const size_t size, int n)
Asynchronously touch memory pages to ensure they're resident.
Parameters
team Thread team to use for task execution
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
memory_touch_async() [2/2]
int xkrt::runtime_t::memory_touch_async (void * ptr, const size_t size, int n) inline
Asynchronously touch memory pages to ensure they're resident.
Convenience wrapper that uses the host driver's team
Parameters
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
Definition at line 698 of file runtime.h.
References XKRT_DRIVER_TYPE_HOST.
memory_unified_advise()
int xkrt::runtime_t::memory_unified_advise (const device_unique_id_t device_unique_id, const void * addr, const size_t size)
Hint to unified memory system about future device access.
Parameters
device_unique_id Global device identifier
addr Memory address
size Size in bytes
Returns
0 on success, non-zero on error
memory_unified_allocate()
void * xkrt::runtime_t::memory_unified_allocate (const device_unique_id_t device_unique_id, const size_t size)
Allocate unified memory accessible by both host and device.
Parameters
device_unique_id Global device identifier (determines which driver to use)
size Size in bytes to allocate
Returns
Pointer to allocated unified memory, or nullptr on failure
memory_unified_deallocate()
void xkrt::runtime_t::memory_unified_deallocate (const device_unique_id_t device_unique_id, void * mem, const size_t size)
Deallocate unified memory.
Parameters
device_unique_id Global device identifier (determines which driver to use)
mem Pointer to unified memory to deallocate
size Size in bytes
memory_unified_prefetch()
int xkrt::runtime_t::memory_unified_prefetch (const device_unique_id_t device_unique_id, const void * addr, const size_t size)
Prefetch unified memory to make it coherent on device.
Parameters
device_unique_id Global device identifier
addr Memory address
size Size in bytes
Returns
0 on success, non-zero on error
memory_unregister()
int xkrt::runtime_t::memory_unregister (void * ptr, size_t size)
Synchronously unregister memory.
Parameters
ptr Memory pointer
size Size in bytes
Returns
0 on success, non-zero on error
memory_unregister_async() [1/3]
int xkrt::runtime_t::memory_unregister_async (team_t * team, void * ptr, const size_t size, int n)
Asynchronously unregister memory using parallel tasks.
Parameters
team Thread team to use for task execution
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
memory_unregister_async() [2/3]
int xkrt::runtime_t::memory_unregister_async (void * ptr, const size_t size, int n) inline
Asynchronously unregister memory using default host team.
Convenience wrapper that uses the host driver's team
Parameters
ptr Memory pointer
size Size in bytes
n Number of parallel tasks
Returns
0 on success, non-zero on error
Definition at line 681 of file runtime.h.
References XKRT_DRIVER_TYPE_HOST.
memory_unregister_async() [3/3]
int xkrt::runtime_t::memory_unregister_async (void * ptr, size_t size)
Asynchronously unregister memory using a single task.
Parameters
ptr Memory pointer
size Size in bytes
Returns
0 on success, non-zero on error
power_start()
void xkrt::runtime_t::power_start (const device_unique_id_t device_unique_id, power_t * pwr)
Start recording energy consumption for a device.
Parameters
device_unique_id Global identifier of the device
[out] pwr Power measurement structure to initialize
power_stop()
void xkrt::runtime_t::power_stop (const device_unique_id_t device_unique_id, power_t * pwr)
Stop recording and retrieve energy consumption.
Parameters
device_unique_id Global identifier of the device
[in,out] pwr Power measurement structure to finalize
reset()
void xkrt::runtime_t::reset (void)
Reset the runtime.
Deallocates all memory replicas and tasks
reset_coherence_controllers()
void xkrt::runtime_t::reset_coherence_controllers (void)
reset_dependence_controllers()
void xkrt::runtime_t::reset_dependence_controllers (void)
stats_report()
void xkrt::runtime_t::stats_report (void)
Report collected runtime statistics.
task_accesses_link()
void xkrt::runtime_t::task_accesses_link (task_t * task, access_t * accesses, task_access_counter_t n)
Set edges with previously inserted accesses in the passed task domain.
task must be a task with TASK_FLAG_DOM
accesses is the list of accesses to linked
n is the number of accesses
task_accesses_put()
void xkrt::runtime_t::task_accesses_put (task_t * task, access_t * accesses, task_access_counter_t n)
Insert an access in the passed task domain. task must be a task with TASK_FLAG_DOM accesses is the list of accesses to put n is the number of accesses
task_accesses_resolve() [1/2]
void xkrt::runtime_t::task_accesses_resolve (access_t * accesses, task_access_counter_t n) inline
Definition at line 730 of file runtime.h.
task_accesses_resolve() [2/2]
void xkrt::runtime_t::task_accesses_resolve (task_t * task, access_t * accesses, task_access_counter_t n)
Do link + put
task_commit() [1/2]
void xkrt::runtime_t::task_commit (task_t * task)
task_commit() [2/2]
template<typename... Args> void xkrt::runtime_t::task_commit (task_t * task, void(*)(Args..., task_t *) F, Args... args) inline
Definition at line 744 of file runtime.h.
task_complete()
void xkrt::runtime_t::task_complete (task_t * task)
task_deallocate_all()
void xkrt::runtime_t::task_deallocate_all (void)
task_dependency_graph_destroy()
void xkrt::runtime_t::task_dependency_graph_destroy (task_dependency_graph_t * tdg)
Destroy a command graph record
task_dependency_graph_record_start()
void xkrt::runtime_t::task_dependency_graph_record_start (task_dependency_graph_t * tdg, bool execute_commands)
Set the 'TASK_FLAG_GRAPH_RECORDING' bit of the currently executing task. It means that all tasks and their emitted commands will be recorded to their task_rec_info_t struct for later replay. If "only-record" is true, then the task executes but emitted commands are not. Else, the task executes so its emitted commands.
task_dependency_graph_record_stop()
void xkrt::runtime_t::task_dependency_graph_record_stop (void)
Unset the 'TASK_FLAG_GRAPH_RECORDING' bit of the currently execution task. Additionally, construct a command graph from all commands previously emitted. Example use: task_spawn() task_spawn() task_wait(); task_dependency_graph_record_start() task_spawn() // A task_spawn() // B task_spawn() // C task_wait() // task executes, but emitted commands are enqueued g = task_dependency_graph_record_stop() // create a command graphs from A, B and C task_dependency_graph_replay(g) // launch commands, returns after all commands completed task_dependency_graph_destroy(g) // destroy the command graph
task_dependency_graph_replay()
void xkrt::runtime_t::task_dependency_graph_replay (task_dependency_graph_t * tdg)
Replay a task dependency graph
task_detachable_decr()
void xkrt::runtime_t::task_detachable_decr (task_t * task)
task_detachable_incr()
void xkrt::runtime_t::task_detachable_incr (task_t * task)
task_dup()
task_t * xkrt::runtime_t::task_dup (const task_t * task)
task_emit_command()
int xkrt::runtime_t::task_emit_command (const device_unique_id_t device_unique_id, const command_queue_type_t qtype, const ocg::command_type_t ctype, const command_flag_t flags, const std::function< void(command_t *)> builder)
The routines bellow emit a command. It increases the current task detach counter by 1. Once the command completed, it decrements the detact counter by 1.
task_enqueue() [1/2]
static void xkrt::runtime_t::task_enqueue (runtime_t * runtime, task_t * task) inline static
Definition at line 779 of file runtime.h.
References task_enqueue().
task_enqueue() [2/2]
void xkrt::runtime_t::task_enqueue (task_t * task)
Referenced by task_enqueue().
task_format_create()
task_format_id_t xkrt::runtime_t::task_format_create (const task_format_t * format)
Creates and registers a new task format.
Copies the provided format data into the formats list at the next available ID.
Parameters
formats Pointer to the task_formats_t repository.
format Pointer to the task_format_t to register.
Returns
The new task_format_id_t assigned to this format.
task_format_get()
task_format_t * xkrt::runtime_t::task_format_get (task_format_id_t fmtid)
Retrieves a task format by its ID.
Parameters
formats Pointer to the task_formats_t repository.
fmtid The task_format_id_t of the format to retrieve.
Returns
A pointer to the corresponding task_format_t, or NULL if the ID is invalid (e.g., XKRT_TASK_FORMAT_NULL or out of bounds).
task_format_put()
task_format_id_t xkrt::runtime_t::task_format_put (const char * label)
Allocates a new task format ID without setting its data.
This function likely reserves a new ID by incrementing next_fmtid and returning its previous value. The caller is then responsible for setting the format's data, perhaps using task_format_set.
Parameters
formats Pointer to the task_formats_t repository.
label The label of the task format
Returns
The allocated task_format_id_t.
task_format_set()
int xkrt::runtime_t::task_format_set (task_format_id_t fmtid, task_format_target_t target, task_format_func_t func)
Sets the function for a specific target on the passed task format.
Parameters
formats Pointer to the task_formats_t repository.
fmtid The task_format_id_t of the format to update.
target The task_format_target_t to set the function for.
func The task_format_func_t implementation for that target.
Returns
0 on success, or an error code if failed.
task_formats_init()
void xkrt::runtime_t::task_formats_init (void)
Initializes the task formats repository.
Sets up the task_formats_t structure, likely by zeroing memory and setting next_fmtid to a starting value (e.g., 1, as XKRT_TASK_FORMAT_NULL is 0).
Parameters
formats Pointer to the task_formats_t instance to initialize.
task_instanciate() [1/2]
template<task_flag_bitfield_t flags> task_t * xkrt::runtime_t::task_instanciate (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t & set_accesses, const task_split_condition_t & split_condition, const task_routine_t & f) inline
Definition at line 947 of file runtime.h.
task_instanciate() [2/2]
template<task_flag_bitfield_t flags> task_t * xkrt::runtime_t::task_instanciate (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t & set_accesses, const task_split_condition_t & split_condition, const void * args, const size_t args_size, const task_format_id_t fmtid) inline
Definition at line 892 of file runtime.h.
References TASK_FLAG_ACCESSES, TASK_FLAG_DEVICE, TASK_FLAG_MOLDABLE, XKRT_UNSPECIFIED_DEVICE_UNIQUE_ID, and XKRT_UNSPECIFIED_TASK_ACCESS.
task_new()
template<bool use_thread_stack = true> task_t * xkrt::runtime_t::task_new (const task_format_id_t fmtid, task_flag_bitfield_t flags, const void * args, const size_t args_size, const task_access_counter_t n_accesses) inline
Definition at line 812 of file runtime.h.
References TASK_FLAG_ACCESSES, TASK_FLAG_GRAPH_RECORDING, TASK_FLAG_RECORD, and XKRT_THREAD_MAX_MEMORY.
task_prog_launch()
template<bool synchronous> void xkrt::runtime_t::task_prog_launch (device_t * device, task_t * task, prog_launcher_t launcher)
Single kernel launcher.
Submit a kernel launch command to the device, then return. The 'launch' is executed by a thread of the device implicit team. If 'synchronous' is set to true, the runtime the kernel to be executed after returning from the launcher (i.e., synchronous execution). Else, it expect the launcher to associate an event to the kernel completion. (i.e., executed asynchronously) The task must be detachable, and completion is associated with the command completion.
'device' is the targeted device 'task' is the currently executing task 'attach_event' if the launcher will attach an event to the command 'launcher' is the kernel launcher
task_spawn() [1/4]
template<task_flag_bitfield_t flags> void xkrt::runtime_t::task_spawn (const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t & set_accesses, const task_split_condition_t & split_condition, const task_routine_t & f) inline
Spawn a task in the currently executing thread team.
Template Parameters
flags Task flags
ac Task access counter specifying the number of accesses
Parameters
device_unique_id The device's global id to use if TASK_FLAG_DEVICE is set
set_accesses Function to set task data accesses if TASK_FLAG_ACCESSES is set
split_condition Function to determine if task should be split if TASK_FLAG_MOLDABLE is set
f Task execution function
Definition at line 968 of file runtime.h.
task_spawn() [2/4]
template<task_access_counter_t ac> void xkrt::runtime_t::task_spawn (const task_accesses_setter_t & set_accesses, const task_routine_t & f) inline
Definition at line 1002 of file runtime.h.
task_spawn() [3/4]
template<task_access_counter_t ac> void xkrt::runtime_t::task_spawn (const task_accesses_setter_t & set_accesses, const task_split_condition_t & split_condition, const task_routine_t & f) inline
Definition at line 991 of file runtime.h.
References XKRT_UNSPECIFIED_DEVICE_UNIQUE_ID.
task_spawn() [4/4]
void xkrt::runtime_t::task_spawn (const task_routine_t & f) inline
Definition at line 984 of file runtime.h.
References XKRT_UNSPECIFIED_DEVICE_UNIQUE_ID.
task_team_enqueue() [1/2]
static void xkrt::runtime_t::task_team_enqueue (runtime_t * runtime, team_t * team, task_t * task) inline static
Definition at line 794 of file runtime.h.
References task_team_enqueue().
task_team_enqueue() [2/2]
void xkrt::runtime_t::task_team_enqueue (team_t * team, task_t * task)
Referenced by task_team_enqueue().
task_thread_enqueue() [1/2]
static void xkrt::runtime_t::task_thread_enqueue (runtime_t * runtime, thread_t * thread, task_t * task) inline static
Definition at line 786 of file runtime.h.
References task_thread_enqueue().
task_thread_enqueue() [2/2]
void xkrt::runtime_t::task_thread_enqueue (thread_t * thread, task_t * task)
Referenced by task_thread_enqueue().
task_wait()
void xkrt::runtime_t::task_wait (void)
team_barrier()
template<bool worksteal = false> void xkrt::runtime_t::team_barrier (team_t * team, thread_t * thread = NULL)
Synchronization barrier - wait until all threads reach this point.
Template Parameters
worksteal Enable work stealing during barrier wait
Parameters
team Pointer to the team
thread Pointer to the calling thread (optional)
team_create()
void xkrt::runtime_t::team_create (team_t * team)
Create a new thread team.
Parameters
team Pointer to the team structure to initialize
team_critical_begin()
void xkrt::runtime_t::team_critical_begin (team_t * team)
Enter a critical section (mutual exclusion)
Parameters
team Pointer to the team
team_critical_end()
void xkrt::runtime_t::team_critical_end (team_t * team)
Exit a critical section.
Parameters
team Pointer to the team
team_get() [1/2]
team_t * xkrt::runtime_t::team_get (const driver_type_t type)
Retrieve the thread team for a specific driver type.
Parameters
type Driver type (e.g., CPU, GPU)
Returns
Pointer to the team, or nullptr if not found
team_get() [2/2]
team_t * xkrt::runtime_t::team_get (const driver_type_t type, const device_driver_id_t device_driver_id)
Retrieve the thread team for a specific device.
Parameters
type Driver type (e.g., CPU, GPU)
device_driver_id Device identifier within the driver
Returns
Pointer to the team, or nullptr if not found
team_get_any()
team_t * xkrt::runtime_t::team_get_any (const driver_type_bitfield_t types)
Retrieve the first available team from multiple driver types.
Parameters
types Bitfield of driver types to search
Returns
Pointer to the first non-null team found, or nullptr
team_join()
void xkrt::runtime_t::team_join (team_t * team)
Wait until all threads have finished and destroy the team.
Parameters
team Pointer to the team to join and destroy
team_parallel_for() [1/3]
void xkrt::runtime_t::team_parallel_for (team_t * team, team_parallel_for_func_t func)
Execute a parallel for loop across team threads (blocking)
Parameters
team Pointer to the team
func Function to execute in parallel by each thread
team_parallel_for() [2/3]
template<int UP, int LOW = 0, int INCR = 1> void xkrt::runtime_t::team_parallel_for (team_t * team, team_parallel_for_i_func_t func) inline
Definition at line 1103 of file runtime.h.
team_parallel_for() [3/3]
void xkrt::runtime_t::team_parallel_for (team_t * team, team_parallel_for_i_func_t func, const int up, const int low = 0, const int incr = 1) inline
Definition at line 1075 of file runtime.h.
team_task_commit()
void xkrt::runtime_t::team_task_commit (team_t * team, task_t * task) inline
Definition at line 1113 of file runtime.h.
team_task_spawn()
template<task_flag_bitfield_t flags> void xkrt::runtime_t::team_task_spawn (team_t * team, const device_unique_id_t device_unique_id, const task_access_counter_t ac, const task_accesses_setter_t & set_accesses, const std::function< bool(task_t *, access_t *)> & split_condition, const std::function< void(runtime_t *, device_t *, task_t *)> & f) inline
Spawn a task within a specific team.
Template Parameters
ac Task access counter specifying the number of data accesses
has_set_accesses Flag indicating if access setter is provided
has_split_condition Flag indicating if split condition is provided
Parameters
team Target team for task execution
set_accesses Function to set task data accesses
split_condition Function to determine if task should be split
f Task execution function
Definition at line 1130 of file runtime.h.
thread_getaffinity()
static void xkrt::runtime_t::thread_getaffinity (cpu_set_t & cpuset) static
Retrieve the CPU affinity mask of the calling thread.
Parameters
[out] cpuset CPU set to be filled with the current thread's affinity
thread_setaffinity()
static void xkrt::runtime_t::thread_setaffinity (cpu_set_t & cpuset) static
Bind the calling thread to the specified CPU set.
Parameters
cpuset CPU set defining which CPUs the thread can run on
Member Data Documentation
[struct]
struct { ... } xkrt::runtime_t::advised
commited
stats_int_t xkrt::runtime_t::commited
Number of tasks committed.
Definition at line 1385 of file runtime.h.
completed
stats_int_t xkrt::runtime_t::completed
Number of tasks completed.
Definition at line 1386 of file runtime.h.
conf
conf_t xkrt::runtime_t::conf
User configuration.
Definition at line 97 of file runtime.h.
device
stats_int_t xkrt::runtime_t::device
Device-side advised allocations.
Device-side prefetched data.
Definition at line 1394 of file runtime.h.
drivers
drivers_t xkrt::runtime_t::drivers
List of registered device drivers.
Definition at line 81 of file runtime.h.
file_read_async
task_format_id_t xkrt::runtime_t::file_read_async
Async file read task format ID.
Definition at line 93 of file runtime.h.
file_write_async
task_format_id_t xkrt::runtime_t::file_write_async
Async file write task format ID.
Definition at line 94 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::formats
Task format registry.
host
stats_int_t xkrt::runtime_t::host
Host-side advised allocations.
Host-side prefetched data.
Definition at line 1395 of file runtime.h.
host_capture
task_format_id_t xkrt::runtime_t::host_capture
Host capture task format ID.
Definition at line 88 of file runtime.h.
list
task_formats_t xkrt::runtime_t::list
Complete list of task formats.
Definition at line 87 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::memory
memory_copy_async
task_format_id_t xkrt::runtime_t::memory_copy_async
Async memory copy task format ID.
Definition at line 89 of file runtime.h.
memory_register_async
task_format_id_t xkrt::runtime_t::memory_register_async
Async memory registration format ID.
Definition at line 91 of file runtime.h.
memory_touch_async
task_format_id_t xkrt::runtime_t::memory_touch_async
Async memory touch task format ID.
Definition at line 90 of file runtime.h.
memory_unregister_async
task_format_id_t xkrt::runtime_t::memory_unregister_async
Async memory unregistration format ID.
Definition at line 92 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::prefetched
registered
stats_int_t xkrt::runtime_t::registered
Memory regions registered.
Definition at line 1390 of file runtime.h.
registered_memory
std::map<uintptr_t, size_t> xkrt::runtime_t::registered_memory
Map of registered memory segments (addr -> size)
Definition at line 102 of file runtime.h.
registered_pages
IntervalSet<uintptr_t> xkrt::runtime_t::registered_pages
Set of registered memory page intervals.
Definition at line 106 of file runtime.h.
router
RouterAffinity xkrt::runtime_t::router
Memory router used by the MCC.
Definition at line 99 of file runtime.h.
state
std::atomic<state_t> xkrt::runtime_t::state
Current runtime state (atomic)
Definition at line 79 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::stats
Runtime statistics collection.
submitted
stats_int_t xkrt::runtime_t::submitted
Number of tasks submitted.
Definition at line 1384 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::tasks[XKRT_TASK_FORMAT_MAX]
topology
hwloc_topology_t xkrt::runtime_t::topology
Hardware locality topology (read-only, initialized at startup)
Definition at line 109 of file runtime.h.
[struct]
struct { ... } xkrt::runtime_t::unified
unregistered
stats_int_t xkrt::runtime_t::unregistered
Memory regions unregistered.
Definition at line 1391 of file runtime.h.
The documentation for this struct was generated from the following file:
include/xkrt/runtime.h